[project]
name = "bnc"
version = "0.1.0"
description = "Library for the bulls and cows game"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "flake8>=7.3.0",
    "isort>=6.0.1",
    "pep8-naming>=0.15.1",
    "pytest>=8.4.1",
]
